// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnJh4nOe-z0FafakRKEKeYg9OoEaT8Eag',
    appId: '1:488399517239:web:894dcbe001bb723105f1b2',
    messagingSenderId: '488399517239',
    projectId: 'test-672ed',
    authDomain: 'test-672ed.firebaseapp.com',
    storageBucket: 'test-672ed.appspot.com',
    measurementId: 'G-B5ERFSVHFC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8eZ6NL4EG2Z9J6t8-k6f6WSC79eqzOaY',
    appId: '1:488399517239:android:7e89c7fe8a99769d05f1b2',
    messagingSenderId: '488399517239',
    projectId: 'test-672ed',
    storageBucket: 'test-672ed.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC08ndQwCdSwRp37PNQDbrUGdnOItybq9I',
    appId: '1:488399517239:ios:5551e85097dd5d6d05f1b2',
    messagingSenderId: '488399517239',
    projectId: 'test-672ed',
    storageBucket: 'test-672ed.appspot.com',
    iosBundleId: 'com.example.wonderworld',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC08ndQwCdSwRp37PNQDbrUGdnOItybq9I',
    appId: '1:488399517239:ios:b773124f38cae96e05f1b2',
    messagingSenderId: '488399517239',
    projectId: 'test-672ed',
    storageBucket: 'test-672ed.appspot.com',
    iosBundleId: 'com.example.wonderworld.RunnerTests',
  );
}
