// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJjD_PuCNPv82US_6QM5h5Aj58g4q8kJQ',
    appId: '1:455557837986:android:52ffcff97dbec5a13ed3fb',
    messagingSenderId: '455557837986',
    projectId: 'wonderworld-e8bac',
    databaseURL: 'https://wonderworld-e8bac-default-rtdb.firebaseio.com',
    storageBucket: 'wonderworld-e8bac.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcWDUue4lcXBabsStb3UM6ubIfo9-ndKw',
    appId: '1:455557837986:ios:4d9a43095764ac5d3ed3fb',
    messagingSenderId: '455557837986',
    projectId: 'wonderworld-e8bac',
    databaseURL: 'https://wonderworld-e8bac-default-rtdb.firebaseio.com',
    storageBucket: 'wonderworld-e8bac.appspot.com',
    iosBundleId: 'com.example.wonderworld',
  );
}
